/**
 * Stock Symbol to Company Name Mapping
 * Lightweight client-safe version
 */

// Symbol -> Company Name map
const SYMBOL_NAMES: Record<string, string> = {
  // Technology
  'AAPL': 'Apple Inc.',
  'MSFT': 'Microsoft Corporation',
  'GOOGL': 'Alphabet Inc. Class A',
  'GOOG': 'Alphabet Inc. Class C',
  'AMZN': 'Amazon.com Inc.',
  'NVDA': 'NVIDIA Corporation',
  'META': 'Meta Platforms Inc.',
  'TSLA': 'Tesla Inc.',
  'AVGO': 'Broadcom Inc.',
  'ORCL': 'Oracle Corporation',
  'CRM': 'Salesforce Inc.',
  'ADBE': 'Adobe Inc.',
  'NFLX': 'Netflix Inc.',
  'AMD': 'Advanced Micro Devices Inc.',
  'INTC': 'Intel Corporation',
  'CSCO': 'Cisco Systems Inc.',
  'QCOM': 'QUALCOMM Inc.',
  'TXN': 'Texas Instruments Inc.',
  'AMAT': 'Applied Materials Inc.',
  'MU': 'Micron Technology Inc.',
  'TSM': 'Taiwan Semiconductor Manufacturing',
  'ASML': 'ASML Holding NV',
  'KLAC': 'KLA Corporation',
  'LRCX': 'Lam Research Corporation',
  'MRVL': 'Marvell Technology Inc.',
  'ARM': 'Arm Holdings plc',
  'ACN': 'Accenture plc',
  'INTU': 'Intuit Inc.',
  'NOW': 'ServiceNow Inc.',
  'IBM': 'International Business Machines',
  'SNOW': 'Snowflake Inc.',
  'PANW': 'Palo Alto Networks Inc.',
  'CRWD': 'CrowdStrike Holdings Inc.',
  'NET': 'Cloudflare Inc.',
  'DDOG': 'Datadog Inc.',
  'MDB': 'MongoDB Inc.',
  'TEAM': 'Atlassian Corporation',
  'WDAY': 'Workday Inc.',
  'FTNT': 'Fortinet Inc.',
  'ZS': 'Zscaler Inc.',
  'OKTA': 'Okta Inc.',
  'TWLO': 'Twilio Inc.',
  'SPLK': 'Splunk Inc.',
  'VEEV': 'Veeva Systems Inc.',
  'UBER': 'Uber Technologies Inc.',
  'LYFT': 'Lyft Inc.',
  'SQ': 'Block Inc.',
  'SHOP': 'Shopify Inc.',
  'ROKU': 'Roku Inc.',
  'ZM': 'Zoom Video Communications Inc.',
  'DOCU': 'DocuSign Inc.',

  // Financials
  'BRK.B': 'Berkshire Hathaway Inc. Class B',
  'JPM': 'JPMorgan Chase & Co.',
  'V': 'Visa Inc.',
  'MA': 'Mastercard Inc.',
  'BAC': 'Bank of America Corp.',
  'WFC': 'Wells Fargo & Co.',
  'GS': 'Goldman Sachs Group Inc.',
  'MS': 'Morgan Stanley',
  'C': 'Citigroup Inc.',
  'BLK': 'BlackRock Inc.',
  'SCHW': 'Charles Schwab Corp.',
  'AXP': 'American Express Co.',
  'SPGI': 'S&P Global Inc.',
  'SOFI': 'SoFi Technologies Inc.',
  'COIN': 'Coinbase Global Inc.',
  'PYPL': 'PayPal Holdings Inc.',
  'MARA': 'Marathon Digital Holdings Inc.',
  'RIOT': 'Riot Platforms Inc.',
  'USB': 'U.S. Bancorp',
  'PNC': 'PNC Financial Services',
  'TFC': 'Truist Financial Corporation',
  'COF': 'Capital One Financial Corp.',
  'AON': 'Aon plc',
  'MMC': 'Marsh & McLennan Companies',
  'AIG': 'American International Group',
  'MET': 'MetLife Inc.',
  'PRU': 'Prudential Financial Inc.',
  'AFL': 'Aflac Inc.',
  'ALL': 'Allstate Corporation',
  'TRV': 'Travelers Companies Inc.',
  'PGR': 'Progressive Corporation',
  'CB': 'Chubb Limited',

  // Healthcare
  'UNH': 'UnitedHealth Group Inc.',
  'JNJ': 'Johnson & Johnson',
  'LLY': 'Eli Lilly and Co.',
  'ABBV': 'AbbVie Inc.',
  'MRK': 'Merck & Co. Inc.',
  'PFE': 'Pfizer Inc.',
  'TMO': 'Thermo Fisher Scientific Inc.',
  'ABT': 'Abbott Laboratories',
  'DHR': 'Danaher Corporation',
  'AMGN': 'Amgen Inc.',
  'GILD': 'Gilead Sciences Inc.',
  'CVS': 'CVS Health Corporation',
  'ISRG': 'Intuitive Surgical Inc.',
  'VRTX': 'Vertex Pharmaceuticals Inc.',
  'REGN': 'Regeneron Pharmaceuticals',
  'BSX': 'Boston Scientific Corporation',
  'SYK': 'Stryker Corporation',
  'ELV': 'Elevance Health Inc.',
  'CI': 'Cigna Group',
  'HUM': 'Humana Inc.',
  'ZTS': 'Zoetis Inc.',
  'BIIB': 'Biogen Inc.',
  'IDXX': 'IDEXX Laboratories Inc.',
  'IQV': 'IQVIA Holdings Inc.',
  'A': 'Agilent Technologies Inc.',
  'DXCM': 'DexCom Inc.',
  'ALGN': 'Align Technology Inc.',

  // Consumer
  'WMT': 'Walmart Inc.',
  'HD': 'Home Depot Inc.',
  'PG': 'Procter & Gamble Co.',
  'KO': 'Coca-Cola Co.',
  'PEP': 'PepsiCo Inc.',
  'COST': 'Costco Wholesale Corp.',
  'MCD': "McDonald's Corp.",
  'NKE': 'Nike Inc.',
  'SBUX': 'Starbucks Corporation',
  'TGT': 'Target Corporation',
  'LOW': "Lowe's Companies Inc.",
  'BKNG': 'Booking Holdings Inc.',
  'MAR': 'Marriott International Inc.',
  'HLT': 'Hilton Worldwide Holdings',
  'YUM': 'Yum! Brands Inc.',
  'CMG': 'Chipotle Mexican Grill Inc.',
  'ORLY': "O'Reilly Automotive Inc.",
  'AZO': 'AutoZone Inc.',
  'GM': 'General Motors Co.',
  'F': 'Ford Motor Co.',
  'DHI': 'D.R. Horton Inc.',
  'LEN': 'Lennar Corporation',
  'NVR': 'NVR Inc.',
  'RCL': 'Royal Caribbean Cruises',
  'CCL': 'Carnival Corporation',
  'NCLH': 'Norwegian Cruise Line Holdings',
  'PM': 'Philip Morris International',
  'MO': 'Altria Group Inc.',
  'CL': 'Colgate-Palmolive Co.',
  'KMB': 'Kimberly-Clark Corporation',
  'GIS': 'General Mills Inc.',
  'K': 'Kellogg Co.',
  'HSY': 'Hershey Co.',
  'MDLZ': 'Mondelez International Inc.',
  'STZ': 'Constellation Brands Inc.',
  'TAP': 'Molson Coors Beverage Co.',
  'KR': 'Kroger Co.',
  'SYY': 'Sysco Corporation',
  'RIVN': 'Rivian Automotive Inc.',
  'LCID': 'Lucid Group Inc.',
  'NIO': 'NIO Inc.',
  'GME': 'GameStop Corp.',
  'ABNB': 'Airbnb Inc.',

  // Energy
  'XOM': 'Exxon Mobil Corporation',
  'CVX': 'Chevron Corporation',
  'COP': 'ConocoPhillips',
  'SLB': 'Schlumberger NV',
  'EOG': 'EOG Resources Inc.',
  'MPC': 'Marathon Petroleum Corp.',
  'PSX': 'Phillips 66',

  // Industrials
  'BA': 'Boeing Co.',
  'CAT': 'Caterpillar Inc.',
  'GE': 'General Electric Co.',
  'HON': 'Honeywell International Inc.',
  'UPS': 'United Parcel Service Inc.',
  'RTX': 'RTX Corporation',
  'LMT': 'Lockheed Martin Corp.',
  'DE': 'Deere & Co.',

  // Communication Services
  'DIS': 'Walt Disney Co.',
  'CMCSA': 'Comcast Corporation',
  'VZ': 'Verizon Communications Inc.',
  'T': 'AT&T Inc.',
  'TMUS': 'T-Mobile US Inc.',
  'AMC': 'AMC Entertainment Holdings Inc.',
  'SNAP': 'Snap Inc.',
  'RBLX': 'Roblox Corporation',

  // Real Estate
  'PLD': 'Prologis Inc.',
  'AMT': 'American Tower Corporation',
  'SPG': 'Simon Property Group Inc.',
  'CCI': 'Crown Castle Inc.',
  'EQIX': 'Equinix Inc.',
  'DLR': 'Digital Realty Trust Inc.',

  // Materials
  'LIN': 'Linde plc',
  'APD': 'Air Products and Chemicals Inc.',
  'SHW': 'Sherwin-Williams Co.',
  'NEM': 'Newmont Corporation',
  'FCX': 'Freeport-McMoRan Inc.',

  // Utilities
  'NEE': 'NextEra Energy Inc.',
  'DUK': 'Duke Energy Corporation',
  'SO': 'Southern Co.',
  'D': 'Dominion Energy Inc.',
  'AEP': 'American Electric Power',
  'EXC': 'Exelon Corporation',

  // High-Volume Stocks
  'PLTR': 'Palantir Technologies Inc.',
};

/**
 * Get company name for a stock symbol
 * @param symbol Stock ticker symbol (e.g., 'AAPL')
 * @returns Company name or the symbol itself if not found
 */
export function getCompanyName(symbol: string): string {
  return SYMBOL_NAMES[symbol] || symbol;
}
